# Generated by Django 2.2.1 on 2019-06-03 19:39

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('tache', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardList',
            new_name='ListList',
        ),
    ]
