# Generated by Django 2.2.1 on 2019-06-03 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0004_auto_20190603_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=100, verbose_name='Board')),
                ('board_background', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
            },
        ),
        migrations.AddField(
            model_name='listlist',
            name='list_board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tache.ListBoard'),
        ),
    ]
