# Generated by Django 2.2.1 on 2019-06-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0005_auto_20190603_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='listboard',
            name='board_active_status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
